# Generated by Django 4.1.5 on 2023-09-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_comment_created_at_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite_product',
            name='owner_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
