# Generated by Django 4.1.5 on 2023-09-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_delete_ftest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='desc',
        ),
    ]
